#!/bin/csh -efx
# This script was automatically generated by /home/xiaoyuz1/data/scripts/doBlastzChainNet.pl
# from /home/xiaoyuz1/data/genomes/DEF_hc
# It is to be executed on xiaoyuz1@lanec1.compbio.cs.cmu.edu in /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain .
# It generates nets (without repeat/gap stats -- those are added later on
# xiaoyuz1@lanec1.compbio.cs.cmu.edu) from chains, and generates axt, maf and .over.chain from the nets.
# This script will fail if any of its commands fail.

cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain

# Make nets ("noClass", i.e. without rmsk/class stats which are added later):
chainPreNet  hg38-chr17.felCat8-chrE1.all.chain.gz /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.chrom.sizes stdout \
| chainNet  stdin -minSpace=1 /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.chrom.sizes stdout /dev/null \
| netSyntenic stdin noClass.net

# Make liftOver chains:
netChainSubset -verbose=0 noClass.net hg38-chr17.felCat8-chrE1.all.chain.gz stdout \
| chainStitchId stdin stdout | gzip -c > hg38-chr17.felCat8-chrE1.over.chain.gz

# Make axtNet for download: one .axt per hg38-chr17 seq.
netSplit noClass.net net
cd ..
mkdir axtNet
foreach f (axtChain/net/*.net)
netToAxt $f axtChain/chain/$f:t:r.chain \
  /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.2bit /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.2bit stdout \
  | axtSort stdin stdout \
  | gzip -c > axtNet/$f:t:r.hg38-chr17.felCat8-chrE1.net.axt.gz
end

# Make mafNet for multiz: one .maf per hg38-chr17 seq.
mkdir mafNet
foreach f (axtNet/*.hg38-chr17.felCat8-chrE1.net.axt.gz)
  axtToMaf -tPrefix=hg38-chr17. -qPrefix=felCat8-chrE1. $f \
        /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.chrom.sizes \
        stdout \
  | gzip -c > mafNet/$f:t:r:r:r:r:r.maf.gz
end
mkdir -p bigMaf
echo "##maf version=1 scoring=blastz" > bigMaf/hg38-chr17.felCat8-chrE1.net.maf
zegrep -h -v "^#" mafNet/*.maf.gz >> bigMaf/hg38-chr17.felCat8-chrE1.net.maf
echo "##eof maf" >> bigMaf/hg38-chr17.felCat8-chrE1.net.maf
gzip bigMaf/hg38-chr17.felCat8-chrE1.net.maf
cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/bigMaf
wget -O bigMaf.as 'http://genome-source.soe.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/lib/bigMaf.as'
wget -O mafSummary.as 'http://genome-source.soe.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/lib/mafSummary.as'
mafToBigMaf hg38-chr17 hg38-chr17.felCat8-chrE1.net.maf.gz stdout \
  | sort -k1,1 -k2,2n > hg38-chr17.felCat8-chrE1.net.txt
bedToBigBed -type=bed3+1 -as=bigMaf.as -tab \
  hg38-chr17.felCat8-chrE1.net.txt  /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes hg38-chr17.felCat8-chrE1.net.bb
hgLoadMafSummary -minSeqSize=1 -test hg38-chr17 hg38-chr17.felCat8-chrE1.net.summary \
  hg38-chr17.felCat8-chrE1.net.maf.gz
cut -f2- hg38-chr17.felCat8-chrE1.net.summary.tab | sort -k1,1 -k2,2n \
  > hg38-chr17.felCat8-chrE1.net.summary.bed
bedToBigBed -type=bed3+4 -as=mafSummary.as -tab \
        hg38-chr17.felCat8-chrE1.net.summary.bed /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes \
        hg38-chr17.felCat8-chrE1.net.summary.bb
rm -f hg38-chr17.felCat8-chrE1.net.txt hg38-chr17.felCat8-chrE1.net.summary.tab \
        hg38-chr17.felCat8-chrE1.net.summary.bed
