#!/bin/csh -efx
# This script was automatically generated by /home/xiaoyuz1/data/scripts/doBlastzChainNet.pl
# from /home/xiaoyuz1/data/genomes/DEF_hc
# It is to be executed on xiaoyuz1@lanec1.compbio.cs.cmu.edu in /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain .
# It filters the net for synteny and creates syntenic net MAF files for
# multiz. Use this option when the query genome is high-coverage and not
# too distant from the reference.  Suppressed unless -syntenicNet is included.
# This script will fail if any of its commands fail.

cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain

netFilter -syn hg38-chr17.felCat8-chrE1.net.gz | gzip -c > hg38-chr17.felCat8-chrE1.syn.net.gz
netChainSubset -verbose=0 hg38-chr17.felCat8-chrE1.syn.net.gz hg38-chr17.felCat8-chrE1.all.chain.gz stdout \
  | chainStitchId stdin stdout | gzip -c > hg38-chr17.felCat8-chrE1.syn.chain.gz
set lineCount = `zcat hg38-chr17.felCat8-chrE1.syn.chain.gz | wc -l`
if ($lineCount > 0) then
  hgLoadChain -test -noBin -tIndex hg38-chr17 chainSynFelCat8-chrE1 hg38-chr17.felCat8-chrE1.syn.chain.gz
  wget -O bigChain.as 'http://genome-source.soe.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/lib/bigChain.as'
  wget -O bigLink.as 'http://genome-source.soe.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/lib/bigLink.as'
  sed 's/.000000//' chain.tab | awk 'BEGIN {OFS="\t"} {print $2, $4, $5, $11, 1000, $8, $3, $6, $7, $9, $10, $1}' > chainSynFelCat8-chrE1.tab
  bedToBigBed -type=bed6+6 -as=bigChain.as -tab chainSynFelCat8-chrE1.tab /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes chainSynFelCat8-chrE1.bb
  awk 'BEGIN {OFS="\t"} {print $1, $2, $3, $5, $4}' link.tab | sort -k1,1 -k2,2n > chainSynFelCat8-chrE1Link.tab
  bedToBigBed -type=bed4+1 -as=bigLink.as -tab chainSynFelCat8-chrE1Link.tab /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes chainSynFelCat8-chrE1Link.bb
  set totalBases = `ave -col=2 /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes | grep "^total" | awk '{printf "%d", $2}'`
  set basesCovered = `bedSingleCover.pl chainSynFelCat8-chrE1Link.tab | ave -col=4 stdin | grep "^total" | awk '{printf "%d", $2}'`
  set percentCovered = `echo $basesCovered $totalBases | awk '{printf "%.3f", 100.0*$1/$2}'`
  printf "%d bases of %d (%s%%) in intersection\n" "$basesCovered" "$totalBases" "$percentCovered" > ../fb.hg38-chr17.chainSyn.FelCat8-chrE1Link.txt
netFilter -minGap=10 hg38-chr17.felCat8-chrE1.syn.net.gz \
  | hgLoadNet -test -noBin -warn -verbose=0 hg38-chr17 netSynFelCat8-chrE1 stdin
mv align.tab netSynFelCat8-chrE1.tab
endif
rm -f link.tab
rm -f chain.tab
if ($lineCount > 0) then
  netToAxt hg38-chr17.felCat8-chrE1.syn.net.gz hg38-chr17.felCat8-chrE1.all.chain.gz \
    /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.2bit /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.2bit stdout \
    | axtSort stdin stdout \
    | axtToMaf -tPrefix=hg38-chr17. -qPrefix=felCat8-chrE1. stdin \
      /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.chrom.sizes \
      stdout \
  | gzip -c > hg38-chr17.felCat8-chrE1.synNet.maf.gz
  md5sum hg38-chr17.felCat8-chrE1.syn.net.gz hg38-chr17.felCat8-chrE1.synNet.maf.gz > synNet.md5sum.txt
endif
if ($lineCount > 0) then
  mkdir -p ../bigMaf
  cd ../bigMaf
  wget -O bigMaf.as 'http://genome-source.soe.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/lib/bigMaf.as'
  wget -O mafSummary.as 'http://genome-source.soe.ucsc.edu/gitweb/?p=kent.git;a=blob_plain;f=src/hg/lib/mafSummary.as'
  mafToBigMaf hg38-chr17 ../axtChain/hg38-chr17.felCat8-chrE1.synNet.maf.gz stdout \
    | sort -k1,1 -k2,2n > hg38-chr17.felCat8-chrE1.synNet.txt
  bedToBigBed -type=bed3+1 -as=bigMaf.as -tab  hg38-chr17.felCat8-chrE1.synNet.txt \
    /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes hg38-chr17.felCat8-chrE1.synNet.bb
  hgLoadMafSummary -minSeqSize=1 -test hg38-chr17 hg38-chr17.felCat8-chrE1.synNet.summary \
        ../axtChain/hg38-chr17.felCat8-chrE1.synNet.maf.gz
  cut -f2- hg38-chr17.felCat8-chrE1.synNet.summary.tab | sort -k1,1 -k2,2n \
        > hg38-chr17.felCat8-chrE1.synNet.summary.bed
  bedToBigBed -type=bed3+4 -as=mafSummary.as -tab \
        hg38-chr17.felCat8-chrE1.synNet.summary.bed \
        /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes hg38-chr17.felCat8-chrE1.synNet.summary.bb
  rm -f hg38-chr17.felCat8-chrE1.synNet.txt hg38-chr17.felCat8-chrE1.synNet.summary.tab \
        hg38-chr17.felCat8-chrE1.synNet.summary.bed
endif
