#!/bin/csh -efx
# This script was automatically generated by /home/xiaoyuz1/data/scripts/doBlastzChainNet.pl
# from /home/xiaoyuz1/data/genomes/DEF_hc
# It is to be executed on xiaoyuz1@lanec1.compbio.cs.cmu.edu in /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz .
# It sets up and performs the big cluster blastz run.
# This script will fail if any of its commands fail.

cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz

/home/xiaoyuz1/gensub2 hg38-chr17.lst felCat8-chrE1.lst gsub jobList
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl make jobListTest jobList -q short
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl check jobListTest
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl time jobListTest > run.time
cat run.time
