#!/bin/bash
# This script was automatically generated by /home/xiaoyuz1/data/scripts/doBlastzChainNet.pl
# from /home/xiaoyuz1/data/genomes/DEF_hc
# It is to be executed on xiaoyuz1@lanec1.compbio.cs.cmu.edu in /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz .
# It computes partitions of target and query sequences into chunks of the
# specified size for the blastz cluster run.  The actual splitting of
# sequence is not performed here, but later on by blastz cluster jobs.
# This script will fail if any of its commands fail.
# fail on any error:
set -xbeEu -o pipefail

cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz

/home/xiaoyuz1/data/scripts/partitionSequence.pl 800000 1000 /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.2bit /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.chrom.sizes -xdir xdir.sh -rawDir ../psl 10 -lstDir tParts > hg38-chr17.lst
export L1=`wc -l < hg38-chr17.lst`
/home/xiaoyuz1/data/scripts/partitionSequence.pl 400000 0 /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.2bit /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.chrom.sizes 300 -lstDir qParts > felCat8-chrE1.lst
export L2=`wc -l < felCat8-chrE1.lst`
export L=`echo $L1 $L2 | awk '{print $1*$2}'`
echo "cluster batch jobList size: $L = $L1 * $L2"
if [ -d tParts ]; then
  echo 'constructing tParts/*.2bit files'
  ls tParts/*.lst | sed -e 's#tParts/##; s#.lst##;' | while read tPart
  do
    sed -e 's#.*.2bit:##;' tParts/$tPart.lst \
      | twoBitToFa -seqList=stdin /home/xiaoyuz1/data/genomes/hg38/hg38-chr17.2bit stdout \
        | faToTwoBit stdin tParts/$tPart.2bit
  done
fi
if [ -d qParts ]; then
  echo 'constructing qParts/*.2bit files'
  ls qParts/*.lst | sed -e 's#qParts/##; s#.lst##;' | while read qPart
  do
    sed -e 's#.*.2bit:##;' qParts/$qPart.lst \
      | twoBitToFa -seqList=stdin /home/xiaoyuz1/data/genomes/felCat8/felCat8-chrE1.2bit stdout \
        | faToTwoBit stdin qParts/$qPart.2bit
  done
fi
