#!/bin/csh -efx
# This script was automatically generated by /home/xiaoyuz1/data/scripts/doBlastzChainNet.pl
# from /home/xiaoyuz1/data/genomes/DEF_hc
# It is to be executed on xiaoyuz1@lanec1.compbio.cs.cmu.edu in /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6 .
# It cleans up files after a successful blastz/chain/net/install series.
# It uses rm -f so failures should be ignored (e.g. if a partial cleanup has
# already been performed).
# This script will fail if any of its commands fail.

cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6

rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/psl/

rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/run/chain/
rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/run/err/
rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz/err/
# avoid no-match error exit when *.2bit does not exist
/bin/csh -c "rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz/tParts/*.2bit || true"
/bin/csh -c "rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz/qParts/*.2bit || true"
rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.cat/err/
rm -f  /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/noClass.net
rm -f  /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.blastz/batch.bak
rm -f  /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.cat/batch.bak
rm -f  /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/run/batch.bak
rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/net/
rm -fr /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/chain/
