#!/bin/csh -efx
# This script was automatically generated by /home/xiaoyuz1/data/scripts/doBlastzChainNet.pl
# from /home/xiaoyuz1/data/genomes/DEF_hc
# It is to be executed on xiaoyuz1@lanec1.compbio.cs.cmu.edu in /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/run .
# It sets up and performs a small cluster run to chain all alignments
# to each target sequence.
# This script will fail if any of its commands fail.

cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/axtChain/run

chmod a+x chain.csh
/home/xiaoyuz1/gensub2 pslParts.lst single gsub jobList
mkdir chain liftedChain
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl make jobListTest jobList -q short
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl check jobListTest
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl time jobListTest > run.time
cat run.time
rmdir liftedChain
