#!/bin/csh -efx
# This script was automatically generated by /home/xiaoyuz1/data/scripts/doBlastzChainNet.pl
# from /home/xiaoyuz1/data/genomes/DEF_hc
# It is to be executed on xiaoyuz1@lanec1.compbio.cs.cmu.edu in /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.cat .
# It sets up and performs a small cluster run to concatenate all files in
# each subdirectory of ../psl into a per-target-chunk file.
# This script will fail if any of its commands fail.

cd /home/xiaoyuz1/data/genomes/hg38tofelCat8.data.2018-6/run.cat

(cd ../psl; find . -maxdepth 1 -type d | grep '^./') \
        | sed -e 's#/$##; s#^./##' > tParts.lst
chmod a+x cat.csh
/home/xiaoyuz1/gensub2 tParts.lst single gsub jobList
mkdir ../pslParts
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl make jobListTest jobList -q short
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl check jobListTest
/home/xiaoyuz1/parasol-wrapper/paraSlurm.perl time jobListTest > run.time
cat run.time
